apiVersion: v1
kind: Pod
metadata:
  name: fabric
spec:
  containers:
  - name: mc
    image: docker.io/itzg/minecraft-server:latest
    env:
    - name: EULA
      value: "TRUE"
    - name: INIT_MEMORY
      value: 2G
    - name: MAX_MEMORY
      value: "{{MAX_MEMORY}}"
    - name: TYPE
      value: FABRIC
    - name: VERSION
      value: 1.21.1
    - name: SEED
      value: 31563250179158
    - name: REMOVE_OLD_MODS
      value: "TRUE"
    - name: MODS
      value: |
        https://mediafilez.forgecdn.net/files/6427/511/goblintraders-fabric-1.21.1-1.11.2.jar
        https://mediafilez.forgecdn.net/files/5911/983/framework-fabric-1.21.1-0.9.4.jar
        https://cdn.modrinth.com/data/P7dR8mSH/versions/73Q31My7/fabric-api-0.116.0%2B1.21.1.jar
        https://cdn.modrinth.com/data/Ua7DFN59/versions/CbIBPwz2/YungsApi-1.21.1-Fabric-5.1.5.jar
        https://cdn.modrinth.com/data/8BmcQJ2H/versions/PEvrTvgj/geckolib-fabric-1.21.1-4.7.5.1.jar
        https://cdn.modrinth.com/data/8YcE8y4T/versions/zuCKHu8U/Ribbits-1.21.1-Fabric-4.1.2.jar
        https://cdn.modrinth.com/data/9s6osm5g/versions/HpMb5wGb/cloth-config-15.0.140-fabric.jar
        https://cdn.modrinth.com/data/Ha28R6CL/versions/E4WyjCxJ/fabric-language-kotlin-1.13.2%2Bkotlin.2.1.20.jar
        https://cdn.modrinth.com/data/onSQdWhM/versions/L8oOJIG9/libIPN-fabric-1.21-6.5.0.jar
        https://cdn.modrinth.com/data/1bokaNcj/versions/BKURGnp1/Xaeros_Minimap_25.2.6_Fabric_1.21.jar
        https://cdn.modrinth.com/data/EsAfCjCV/versions/b5ZiCjAr/appleskin-fabric-mc1.21-3.0.6.jar
        https://cdn.modrinth.com/data/NcUtCpym/versions/V6mteZg9/XaerosWorldMap_1.39.4_Fabric_1.21.jar
        https://cdn.modrinth.com/data/qQyHxfxd/versions/D8K0KJXM/NoChatReports-FABRIC-1.21.1-v2.9.1.jar
        https://cdn.modrinth.com/data/9eGKb6K1/versions/d0ufppyc/voicechat-fabric-1.21.1-2.5.30.jar
        https://cdn.modrinth.com/data/u6dRKJwZ/versions/OjLMio2T/jei-1.21.1-fabric-19.21.1.304.jar
        https://cdn.modrinth.com/data/O7RBXm3n/versions/mYLsfjt2/InventoryProfilesNext-fabric-1.21-2.1.8.jar
        https://cdn.modrinth.com/data/rlloIFEV/versions/Mse7s79Y/travelersbackpack-fabric-1.21.1-10.1.19.jar
        https://cdn.modrinth.com/data/4sP0LXxp/versions/YqKzhrfs/veinminer-enchant-2.2.2.jar
        https://cdn.modrinth.com/data/OhduvhIc/versions/1NZqjOaM/veinminer-fabric-2.4.2.jar
        https://cdn.modrinth.com/data/aTaCgKLW/versions/jrC1TCfF/silk-all-1.10.7.jar
        https://cdn.modrinth.com/data/fFEIiSDQ/versions/gTcgfFjQ/supplementaries-1.21-3.1.7-fabric.jar
        https://cdn.modrinth.com/data/twkfQtEc/versions/AK7kgIp8/moonlight-1.21-2.18.13-fabric.jar
        https://cdn.modrinth.com/data/t5FRdP87/versions/bdpPtvTn/YungsBetterWitchHuts-1.21.1-Fabric-4.1.1.jar
        https://cdn.modrinth.com/data/tpehi7ww/versions/EUlNXs9V/dungeons-and-taverns-v4.4.4.jar
        https://cdn.modrinth.com/data/joEfVgkn/versions/TuSZSQeB/carryon-fabric-1.21.1-2.2.2.11.jar
        https://cdn.modrinth.com/data/Ht4BfYp6/versions/8h9N9fvs/YungsBridges-1.21.1-Fabric-5.1.1.jar
        https://cdn.modrinth.com/data/LOpKHB2A/versions/nIcT6ztO/waystones-fabric-1.21.1-21.1.18.jar
        https://cdn.modrinth.com/data/MBAkmtvl/versions/KNh0OFys/balm-fabric-1.21.1-21.0.44.jar
        https://cdn.modrinth.com/data/XNlO7sBv/versions/M6eeDRkC/YungsBetterDesertTemples-1.21.1-Fabric-4.1.5.jar
        https://cdn.modrinth.com/data/DjLobEOy/versions/MntMLupc/t_and_t-neoforge-fabric-1.13.2.jar
        https://cdn.modrinth.com/data/cl223EMc/versions/8iGbvXwk/cristellib-fabric-1.2.8.jar
        https://cdn.modrinth.com/data/gc8OEnCC/versions/4qhBEg6J/better-end-21.0.11.jar
        https://cdn.modrinth.com/data/RiN8rDVs/versions/mPmeykPR/worldweaver-21.0.13.jar
        https://cdn.modrinth.com/data/BgNRHReB/versions/TxWM7AW8/bclib-21.0.13.jar
        https://cdn.modrinth.com/data/pJmCFF0p/versions/f0pKpUWd/handcrafted-fabric-1.21.1-4.0.3.jar
        https://cdn.modrinth.com/data/G1hIVOrD/versions/Hf91FuVF/resourcefullib-fabric-1.21-3.0.12.jar
        https://cdn.modrinth.com/data/MpzVLzy5/versions/M1o6hR2m/better-nether-21.0.11.jar
        https://cdn.modrinth.com/data/EltpO5cN/versions/3FjXvOGL/lootr-fabric-1.21-1.10.35.91.jar
        https://cdn.modrinth.com/data/fnAffV0n/versions/MoitXjJY/deeperdarker-fabric-1.21-1.3.3.jar
        https://cdn.modrinth.com/data/ccKDOlHs/versions/JB1fLQnc/owo-lib-0.12.15.4%2B1.21.jar
        https://cdn.modrinth.com/data/BdKIyOLe/versions/2fKkBn4m/boatiview-fabric-0.0.6-1.21.1.jar
        https://cdn.modrinth.com/data/fgmhI8kH/versions/IS8JSyqE/%5Bfabric%5Dctov-3.5.8.jar
        https://cdn.modrinth.com/data/XaDC71GB/versions/GyOXVW9s/lithostitched-fabric-1.21.1-1.4.5.jar
        https://cdn.modrinth.com/data/6iTJugQR/versions/uSU0iJNb/amendments-1.21-1.2.24-fabric.jar
        https://cdn.modrinth.com/data/mSQF1NpT/versions/jxx2pc4h/elytraslot-fabric-9.0.1%2B1.21.1.jar
        https://cdn.modrinth.com/data/5aaWibi9/versions/JagCscwi/trinkets-3.10.0.jar
        https://cdn.modrinth.com/data/x3HZvrj6/versions/JC1GraWr/immersive_aircraft-1.2.4%2B1.21.1-fabric.jar
        https://cdn.modrinth.com/data/zCh7omyG/versions/kOnpndPm/betterarcheology-fabric-1.3.2.jar
        https://cdn.modrinth.com/data/M1953qlQ/versions/dQh99ERC/resourcefulconfig-fabric-1.21-3.0.11.jar
        https://cdn.modrinth.com/data/lhGA9TYQ/versions/Wto0RchG/architectury-13.0.8-fabric.jar
        https://cdn.modrinth.com/data/POQ2i9zu/versions/Co1nYbyH/friendsandfoes-fabric-4.0.5%2Bmc1.21.1.jar
        https://cdn.modrinth.com/data/ulloLmqG/versions/y4yMDiD3/another_furniture-fabric-4.0.0.jar
        https://cdn.modrinth.com/data/Heh3BbSv/versions/t9u0vP6q/gravestones-1.0.9.jar
        https://cdn.modrinth.com/data/ZLKQjA7t/versions/A0zQ8CmQ/pneumonocore-1.1.6.jar
        https://cdn.modrinth.com/data/CFX9ftUJ/versions/V6q02QPT/advancednetherite-fabric-2.2.1-1.21.1.jar
        https://cdn.modrinth.com/data/8DfbfASn/versions/lTNnufP5/DungeonsArise-1.21.1-2.1.64-fabric-release.jar
        https://cdn.modrinth.com/data/P0Mu4wcQ/versions/fa7v7ycL/artifacts-fabric-13.0.4.jar
        https://cdn.modrinth.com/data/3BeIrqZR/versions/RzhrT8Th/Origins-1.13.0-alpha.12%2Bmc.1.21.1.jar
        https://cdn.modrinth.com/data/D5h9NKNI/versions/gdB0WW0x/lavender-0.1.15%2B1.21.jar
        https://cdn.modrinth.com/data/ptzsjBKT/versions/xJnyRm2Q/awesomedungeon-fabric-1.21.1-3.2.0.jar
        https://cdn.modrinth.com/data/DOB2l4oJ/versions/Mu22ObQq/libraryferret-fabric-1.21.1-4.0.0.jar
        https://cdn.modrinth.com/data/1eAoo2KR/versions/equv2TRU/yet_another_config_lib_v3-3.6.6%2B1.21.1-fabric.jar
    ports:
    - containerPort: 25565
      hostPort: "{{HOST_PORT}}"
      protocol: TCP
    volumeMounts:
    - mountPath: /data
      name: minecraft-data
  volumes:
  - name: minecraft-data
    hostPath:
      path: "{{HOST_DIR}}"
      type: DirectoryOrCreate
